# Configuration file for mdbook

[book]
authors = ["Gary Wang"]
language = "en"
multilingual = false
src = "src"
title = "Learning Programming Book"
description = "The example book covers examples."

# [rust]
# edition = "2018"

[build]
build-dir = ".book"
# create-missing = false

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.katex]
# https://katex.org/docs/supported.html
after = ["links"]
macros = "latex-macros.txt"

# [preprocessor.pagetoc]
# install release from "https://github.com/slowsage/mdbook-pagetoc".
#! replaced by "mdbook-theme"

[preprocessor.theme]
# avoid: repeated building when "mdbook serve":
# 1. run "mdbook build" once and set "turn-off = true"
# 2. run "mdbook build" once and comment out this section
# 3. add "theme" to ".gitignore" to skip "mdbook watch" on theme dir.
pagetoc        = true
turn-off       = true
content-max-width         = "77%"
content-main-margin-left  = "4%"
content-main-margin-right = "4%"

pagetoc-width            = "14%"
pagetoc-font-size        = "1rem"  # no use: modify pagetoc.css directly

# sidebar = toc on the left
sidebar-width            = "200px"

root-font-size           = "80%"    # control the main font-size
body-font-size           = "1.2rem"
code-font-size           = "1rem"
sidebar-font-size        = "1rem"    


[output.html]
# theme = "my-theme"
# default-theme = "light"
# preferred-dark-theme = "navy"
# curly-quotes = true
# mathjax-support = true
# Note: The usual delimiters MathJax uses are not yet supported. 
# You can't currently use $$ ... $$ as delimiters and the \[ ... \] 
# delimiters need an extra backslash to work. Hopefully this 
# limitation will be lifted soon.
# copy-fonts = true
additional-css = ["theme/pagetoc.css"]
# Additional javascript will be copied to the build directory.
# NOTE: not sure "MathJax.js"'s functionality
# "theme/MathJax.js"
additional-js  = ["theme/pagetoc.js", "theme/mermaid.min.js", "theme/mermaid-init.js"]  
no-section-label = true
# git-repository-url = "https://github.com/rust-lang/mdBook"
# git-repository-icon = "fa-github"
# edit-url-template = "https://github.com/rust-lang/mdBook/edit/master/guide/{path}"
# site-url = "/example-book/"
# cname = "myproject.rs"
# input-404 = "not-found.md"

[output.html.search]
enable = false  # set to false to avoid [searchindex.json is very large]