site_name: Learning Programming Book
# site_name: !ENV SITE_NAME
# site_name: !ENV SITE_NAME, 'My default site name']
theme: readthedocs
docs_dir: src
site_dir: .site
site_url: https://learn.program.com/mkdocs/
site_description: programming notes for daily use.
site_author: Gary Wang
use_directory_urls: false
# exclude_docs: New in version 1.5
# https://www.mkdocs.org/user-guide/configuration/#exclude_docs
# Don't exclude '.assets' although all other '.*' are excluded
# Note that mkdocs serve does not follow this setting and instead displays excluded documents but with a "DRAFT" mark. To prevent this effect, you can run mkdocs serve --clean.
exclude_docs: |
  _*.md
  index.html
  !/**/.assets/*
nav:
  - 目录: index.md
  - 程序设计语言:
      - Python:
          - 编程基础: ./Python/Python编程基础.md
          - 开发环境: ./Python/Python开发环境.md
          - 数据类型: ./Python/Python数据类型.md
          - 输入输出: ./Python/Python输入输出.md
          - 编程应用: ./Python/Python编程应用.md
          - 图形界面: ./Python/Python图形界面.md
          - 数值计算: ./Python/Python数值计算.md
          - 系统编程: ./Python/Python系统编程.md
          - 高级编程: ./Python/Python高级编程.md
      - Java:
          - 编程基础: ./Java/Java编程基础.md
          - 开发环境:
              - 开发环境: ./Java/Java开发环境.md
              - Maven配置: ./Java/Maven POM.md
          - 数据类型: ./Java/Java数据类型.md
          - 输入输出: ./Java/Java输入输出.md
          - 系统编程: ./Java/Java系统编程.md
          # - 高级特性: ./Java/Java高级编程.md
          # - 编程应用: ./Java/Java编程应用.md
          - Java框架: ./Java/JavaFrameworks.md
          - Scala: ./Java/Scala.md
          - Scala框架: ./Java/ScalaFrameworks.md
      - C#.NET:
          - 编程基础: ./CSharp.NET/CSharp编程基础.md
          - 输入输出: ./CSharp.NET/CSharp输入输出.md
          - 数据容器: ./CSharp.NET/CSharp数据容器.md
          - 数值计算: ./CSharp.NET/CSharp数值计算.md
          - .NET开发: ./CSharp.NET/dotnet开发.md
      - C和C++:
          - Modern C++: ./CC++/Modern C++.md
          - 开发环境: ./CC++/C++开发环境.md
          - 数据容器: ./CC++/C++容器.md
          - 输入输出: ./CC++/输入输出.md
          - 标准库:
              - 标准库: ./CC++/标准库函数.md
              - 数学函数: ./CC++/数学函数.md
      - Web开发:
          - JavaScript: ./JavaScript/JavaScript.md
          - TypeScript: ./JavaScript/TypeScript.md
          - 开发环境: ./JavaScript/JavaScript开发环境.md
          - 前端开发:
              - HTML: ./数据交换语言/HTML.md
              - Angular: ./JavaScript/Angular.md
              - Antd: ./JavaScript/AntdPro.md
          - 后端开发:
              - Express: ./JavaScript/Express.md
      - 开发工具:
          - 正则表达式: ./笔记/正则表达式.md
          - 哈希函数: ./笔记/哈希函数.md
          - Git: ./开发环境/git.md
          - GitLab: ./开发环境/gitlab-cicd.md
          # - Visual Studio: ./开发环境/Visual Studio使用技巧.md
      - 现代编程语言:
          - Julia: ./NewLang/Julia/Julia Language.md
          - Rust: ./NewLang/Rust/rust.md
          - NuShell: ./NewLang/Nushell.md
      # - Perl: ./Perl/Perl.md
  # - 算法: 
  #   - 算法: ./算法/算法.md
  - 操作系统:
      - Linux:
          - 配置管理: ./Linux/Linux配置和管理.md
          - Shell Script: ./Linux/Linux-Shell.md
          - Linux发行版: ./Linux/Linux发行版.md
          - 操作系统原理: ./Linux/操作系统原理.md
          # - 系统编程: ./Linux/Unix环境高级编程.md
          # - 系统编程接口: ./Linux/操作系统接口.md
          # - 图形界面编程: ./图形界面/GTK/GTK.md
          # - 用户界面配置: ./Linux/用户界面配置.md
      - Windows:
          - 配置管理: ./Windows/Windows配置管理.md
          - Windows Shell:
              - PowerShell: ./Windows/Windows Shell.md
              - cmd: ./Windows/cmd.md
          - 应用软件开发: ./Windows/Windows Applications.md
          # - Windows应用开发: ./图形界面/Windows Application.md
          # - Windows现代应用开发: ./图形界面/WindowsModernApplication.md
          - Windows编程接口: ./Windows/Windows API.md
      - 应用软件:
          - 程序开发: ./应用软件/程序开发软件.md
          - 服务器管理: ./应用软件/服务器管理软件.md
          - 网络访问: ./应用软件/网络访问软件.md
          - 网络服务: ./应用软件/网络服务软件.md
          - 文档生成: ./应用软件/文档生成软件.md
          - 文件处理: ./应用软件/文件处理软件.md
          - 协作办公: ./应用软件/协作办公软件.md
          # - 知识管理: ./应用软件/知识管理软件.md
          - 多媒体编辑: ./应用软件/多媒体编辑软件.md
  - 机器学习:
      - 机器学习实践:
          - 机器学习实践: ./机器学习/机器学习实践.md
          - 机器学习平台: ./机器学习/机器学习平台.md
          - scikit-learn: ./机器学习/ScikitLearn.md
          - TensorFlow: ./机器学习/TensorFlow.md
          # - TensorFlow Java API: ./机器学习/TensorFlow Java.md
          # - TensorFlow on Spark: /机器学习/当Spark遇上TensorFlow分布式深度学习框架.md
          - Pytorch: ./机器学习/Pytorch.md
          # - 机器学习资源: ./笔记/MLResources.md
      - 原理与算法:
          - 数学基础: ./机器学习/机器学习的数学基础.md
          - 机器学习算法: ./机器学习/机器学习算法.md
          - 特征降维: ./机器学习/DimensionalityReduction.md
          - 图数据分析: ./机器学习/图数据分析.md
          - 图神经网络: ./机器学习/图神经网络.md
      - 统计学习算法: ./机器学习/统计学习算法.md
  - 数据库:
      - 数据库: ./数据库/数据库简介.md
      - 关系型数据库:
          - SQL语法: ./数据库/SQL语法.md
          - SQL DDL: ./数据库/SQL DDL.md
          - SQL DML: ./数据库/SQL DML.md
          - 数据类型: ./数据库/SQL数据类型.md
          - MySQL: ./数据库/MySQL.md
          - PostgreSQL: ./数据库/PostgreSQL.md
      # - SQLite: ./数据库/sqlite.md
      - Hive SQL: ./数据库/HiveSQL.md
      - ElasticSearch:
          - ElasticSearch: ./数据库/Elasticsearch.md
          - ES查询: ./数据库/Elasticsearch查询.md
          - ES客户端编程接口: ./数据库/ElasticsearchAPI.md
        # - Elasticsearch数据源: ./数据库/Elasticsearch数据源.md
      - Mongodb: ./数据库/Mongodb.md
      - 图数据库: ./数据库/GraphDatabase.md
      - 内存数据库: ./数据库/MemoryCache.md
      # - 高性能计算数据库:
      # - ClickHouse: ./数据库/clickhouse.md
  - 大数据和服务平台:
      - 分布式大数据处理:
          - 分布式大数据处理: ./服务器/分布式大数据处理.md
          # - CDH6安装教程: ./服务器/CDH6大数据集群离线安装.md
          # - Dask on Yarn: ./服务器/Dask on Yarn.md
          # - Metastore: ./服务器/Metastore.md
          - Spark: ./服务器/Spark.md
          - Pyspark: ./服务器/Spark Python API.md
          # - Spark API: ./服务器/Spark Scala API.md
          - 流数据处理: ./服务器/流数据处理.md
      - 容器编排: 
        - 容器: ./服务器/容器编排.md
        - Kubernetes: ./服务器/Kubernetes.md
        # - 微服务: ./服务器/Microservices.md
      - 虚拟化: ./服务器/虚拟化.md
      - 任务编排:
          - Airflow: ./服务器/Airflow.md
  - 其他:
      - 数据标记语言:
          - JSON and YAML: ./数据交换语言/JSON and YAML.md
          - XML: ./数据交换语言/XML.md
      - 网络协议:
          - HTTP: ./Protocols/http.md
          - DNS: ./Protocols/DNS.md
          - IP协议: ./Protocols/Internet Protocol.md
          - RPC: ./Protocols/RPC.md
  # - About: about.md

# markdown_extensions:
#     - smarty
#     - toc:
#         permalink: True
#     - sane_lists

# pip install mkdocs-foo-plugin
# https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins#navigation--page-building
plugins:
  - search
  - section-index # only works for first level section
    # pip install mkdocs-section-index
  - exclude: # - mkdocs-exclude ✔
      glob:
        - "*.tmp"
        - "*.pdf"
        - "*.gz"
        - "*.zip"
        - "CSharp.NET/MediaInfo*"
        - "Java/Java语言与面向对象程序设计*"
      regex:
        - ".*/.(doc|ppt|xls|vsd)x?$"
#     - add-number: # mkdocs-add-number-plugin ❌
#           strict_mode: False
#           order: 2

# 引用块中包含的代码块不能正确被渲染。
# 页面内目录支持(需要插入div块)
